name = "yebomradio"
main = "worker.js"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "RADIO_BUCKET"
bucket_name = "coachdb-files"

[[kv_namespaces]]
binding = "RADIO_KV"
id = "c4c08099c81c4860a0184e7c29562434"

# ADMIN_KEY는 Secret으로 별도 설정
# wrangler secret put ADMIN_KEY

[triggers]
crons = ["0 3 * * *"]
